tables:

  Guarantee:
    sf: "data/raw/guarantee_sf.csv"
    laweb: "data/raw/guarantee_laweb.csv"
    primary_key: "ID"
    dtype_map: null # "data/raw/DTypes_GuaranteeTable_Sf_VS_Laweb.xlsx"

    rules_enabled:
      - V01      # Row count
      - C01      # Missing IDs in LAWEB
      - C02      # Extra IDs in LAWEB
      - S01      # Column count
      - S02      # Column names
      - P01      # PK unique
      - P02      # PK not null
      - CM02     # Full row compare
      - CM03     # Null pattern consistency

    mandatory_fields:
      - ID
      - CODICEIDENTIFICATIVOGARANZIA
      - POSIZIONE_ID


  StoricoReferenteEntita:
    sf: "data/raw/StoricoReferenteEntita_SF.csv"
    laweb: "data/raw/StoricoReferenteEntita_LAWEB.csv"
    primary_key: "ID"
    dtype_map: null

    rules_enabled:
      - V01
      - C01
      - C02
      - S01
      - S02
      - P01
      - P02
      - CM01     # sample-based row compare

    mandatory_fields:
      - ID

  IstanzaAttributoTask:
    sf: "data/raw/IstanzaAttributoTask_SF.csv"
    laweb: "data/raw/IstanzaAttributoTask_LAWEB.csv"
    primary_key: "ID"
    dtype_map: null # "data/raw/DTypes_IstanzaAttributoTask_Sf_VS_Laweb.xlsx"

    rules_enabled:
      - V01      # Row count
      - C01      # Missing IDs in LAWEB
      - C02      # Extra IDs in LAWEB
      - S01      # Column count
      - S02      # Column names
      - P01      # PK unique
      - P02      # PK not null
      - CM02     # Full row compare
      - CM03     # Null pattern consistency

    mandatory_fields:
      - ID

